### ISSUE TITLE
problem with the screen size

### ISSUE THREAD

**Issue by 0x72D0** [Zac-Garby/solar-system#19]
when I lauch the program I got a size problem:
![deepinscreenshot_desktop_20171014115146](https://user-images.githubusercontent.com/16087328/31577273-6d549062-b0d9-11e7-8a30-6f2cdeb51198.png)

and when I change the value in config.h:
![deepinscreenshot_20171014120426](https://user-images.githubusercontent.com/16087328/31577278-9128ec36-b0d9-11e7-9cbe-1e3bb388f6d5.png)

I still have problem....

**Comment by zac-garby** [comment]
Yeah, I know what's going on here. Since I'm on a Retina display, my screen is about 5000x2000 (about that) so I set the screen size to what looked good for me.

It's possible to get the display pixel density and work out sizes from that, but I haven't got round to it yet.

If you (or anyone else) wants to have a go at fixing this, you're welcome, but I'll have a look at it at some point too.
