### ISSUE TITLE
Resources can overflow

### ISSUE THREAD

**Issue by zac-garby** [Zac-Garby/solar-system#51]
If you leave the game running for a few minutes, it's quite likely that the resources will overflow their max values, since they're `int`s. This shouldn't be that hard to fix (probably just as simple as changing them to `long`s)

**Comment by neilkakkar** [comment]
I'll take this up, just to warm up. ( I would like to stick around longer and help out with some of the features. Will be raising issues once I dive into the code to see if it is something I can work on. )

**Comment by zac-garby** [comment]
Nice - thanks :)

**Comment by neilkakkar** [comment]
I'm having troubles compiling this. Does the current build work fine for you?

Also, might be a good idea to mention the version of SFML you are using. I was scratching my head for a while wondering why I was getting some of the errors I was gettting. Turns out, just like CMake isn't the latest on Ubuntu 16, SFML isn't either, it's at 2.3.2 on Ubuntu 16.

This is the current error ( among others)
solar-system/game.cpp:221:83: error: converting to ‘std::vector<std::tuple<Planet*, Planet*, float> >::value_type {aka std::tuple<Planet*, Planet*, float>}’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {Planet* const&, Planet* const&, float&}; <template-parameter-2-2> = void; _Elements = {Planet*, Planet*, float}]’
            edges.push_back({edge.first.first, edge.first.second, edge.second});
                      
Thanks! :)

**Comment by neilkakkar** [comment]
While this is easy to fix ( just using make_tuple( ) instead ), there are some linking errors too.

Specifically, the buiild.make file generated by CMake refers to the .so libs of SFML in /usr/lib/x86_64-linux-gnu/ while they aren't really there.

Hmm, any ideas?

**Comment by zac-garby** [comment]
I think I read somewhere that the `{ ... }` syntax for tuples only works in C++17, so it might be worth changing it to use `make_tuple`.

Regarding the linking error: the .so libs of SFML might only exist in the newer versions of SFML.

**Comment by neilkakkar** [comment]
I see. Yeah, I manually copied the newest SFML lib files to /usr/lib . What's weird is how CMake is looking for them in a different directory. I suspect it has to do something with how FindSFML.cmake works. If I copy the libs to this folder or change the makefile generated to point to the correct path ( which I really shouldn't be doing ), then I start getting the referencing errors for sf elements.

**Comment by zac-garby** [comment]
Oh, I get what you mean. FindSFML.cmake is just copied off the internet somewhere, so I've no idea really how it works. It's definitely strange that it doesn't build for you, since I'm pretty sure a few other people on Ubuntu have managed to build it.

**Comment by tbohne** [comment]
@neilkakkar, I had the same issues you are describing here. I managed to solve them by installing the newest versions of each library, especially SFML - https://www.sfml-dev.org/download/sfml/2.4.2/. You have to purge the previously installed versions to avoid conflicts. You also have to keep in mind to remove the files created by cmake from previous compilation attempts (CMakeCache.txt, ...) before you compile it again. I would recommend the following build process: `mkdir build` --> `cd build` --> `cmake ..` --> `make`.
In that case you just have to remove the whole build folder each time. I adjusted the path to the fonts accordingly and used `make_tuple` to  establish  C++11 compatibility. I created a PR for these small changes.

**Comment by neilkakkar** [comment]
Hey @tbohne ,

Thanks for this! I did upgrade SFML to 2.4.2. Wasn't clearing the cache though.That's a nice tip.
Do you remember doing anything for the dynamic linking? That is where the current error is. Undefined references to sf. Did you have to declare the lib files folder anywhere or something like that?

Thanks!

**Comment by tbohne** [comment]
@neilkakkar, I built SFML myself, here's exactly what I did:
- Clone the repo: https://github.com/SFML/SFML
- I had to install one more lib: `sudo apt-get install libopenal-dev`
- In SFML/:  `cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug -D BUILD_SHARED_LIBS=TRUE .`
- `make -j4`
-  `sudo make install`

That should fix your linking issues ;)

**Comment by neilkakkar** [comment]
Thanks, this worked :) I was using an alternate method for installing SFML, that was giving all the problems. I think this bit should be a part of the COMPILING.md file. If you don't mind, I'll add it there! ( Maybe along with what not to do :P ) or if you prefer, you can do that yourself :)

**Comment by neilkakkar** [comment]
So, regarding the issue. I think it makes sense to have a max value over which this wouldn't go, instead of changing the data type to long. After all, long would be exceeded at some point too. Further, I think the number added to each resource shouldn't be positive always. Instead, something like `randRange(-500,10000)` . Think of it as the population consuming the resource. Actually, at some point, we ought to include consumption and production rates for resources on each planet, instead of random numbers.
I see a lot of `INT_MIN` too. For each, a check for max possible value is what I'm implementing.

Sounds good?

**Comment by tbohne** [comment]
@neilkakkar, glad it worked, updated the COMPILING.md ;)
